export const SEED_DATA = {
  habitaciones: [
    {
      id: 'h1',
      nombre: 'Habitacion 101',
      color: '#4E7D9A',
      precioActual: 800000,
      precioMinimo: 720000,
      estado: 'ocupada',
      inquilinoId: 'i1',
      descripcion: 'Ventana amplia, vista a la avenida.',
      amenidades: ['armario', 'ventana amplia'],
      fechaCreacion: '2024-03-01',
    },
    {
      id: 'h2',
      nombre: 'Habitacion 102',
      color: '#B6684E',
      precioActual: 950000,
      precioMinimo: 860000,
      estado: 'ocupada',
      inquilinoId: 'i2',
      descripcion: 'Cerca de la cocina, ideal para estudiante.',
      amenidades: ['cerca cocina', 'ventilacion'],
      fechaCreacion: '2023-11-01',
    },
    {
      id: 'h3',
      nombre: 'Habitacion Principal',
      color: '#8A6FB1',
      precioActual: 1200000,
      precioMinimo: 1050000,
      estado: 'libre',
      inquilinoId: null,
      descripcion: 'Balcon privado y closet amplio.',
      amenidades: ['balcon', 'closet amplio'],
      fechaCreacion: '2022-05-01',
    },
  ],
  inquilinos: [
    {
      id: 'i1',
      nombre: 'Valentina Rojas',
      telefono: '3001234567',
      email: 'valentina@correo.com',
      cedula: '1010101010',
      habitacionId: 'h1',
      fechaIngreso: '2024-09-15',
      fechaSalida: null,
      diaVencimiento: 5,
      activo: true,
      notas: 'Pago puntual, comunicacion clara.',
    },
    {
      id: 'i2',
      nombre: 'Daniel Mejia',
      telefono: '3015552121',
      email: 'daniel@correo.com',
      cedula: '2020202020',
      habitacionId: 'h2',
      fechaIngreso: '2025-01-02',
      fechaSalida: null,
      diaVencimiento: 5,
      activo: true,
      notas: 'Requiere recordatorios de pago.',
    },
    {
      id: 'i3',
      nombre: 'Laura Pineda',
      telefono: '3028877665',
      email: 'laura@correo.com',
      cedula: '3030303030',
      habitacionId: 'h3',
      fechaIngreso: '2026-02-23',
      fechaSalida: null,
      diaVencimiento: 5,
      activo: true,
      notas: 'Ingreso reciente.',
    },
  ],
  pagos: [
    {
      id: 'p1',
      inquilinoId: 'i1',
      habitacionId: 'h1',
      monto: 800000,
      fecha: '2026-05-02',
      mes: '2026-05',
      tipo: 'arriendo',
      estado: 'pagado',
      metodoPago: 'nequi',
      diasMora: 0,
      notas: 'Pago puntual.',
    },
    {
      id: 'p2',
      inquilinoId: 'i2',
      habitacionId: 'h2',
      monto: 950000,
      fecha: '2026-05-05',
      mes: '2026-05',
      tipo: 'arriendo',
      estado: 'vencido',
      metodoPago: 'transferencia',
      diasMora: 3,
      notas: 'Acuerdo de pago.',
    },
    {
      id: 'p3',
      inquilinoId: 'i3',
      habitacionId: 'h3',
      monto: 1200000,
      fecha: '2026-05-07',
      mes: '2026-05',
      tipo: 'arriendo',
      estado: 'pendiente',
      metodoPago: 'daviplata',
      diasMora: 0,
      notas: 'Recordatorio enviado.',
    },
  ],
  serviciosPublicos: [
    {
      id: 'agua-2026-05',
      servicioId: 'agua',
      nombre: 'Agua y alcantarillado',
      empresa: 'Aguas de Manizales',
      icono: 'Droplet',
      color: '#0EA5E9',
      urlPago:
        'https://portal.aguasdemanizales.com.co/Portal/Modulos/Pagos/InicioPago.aspx',
      urlConsulta:
        'https://www.aguasdemanizales.com.co/Aguas-de-Manizales-SA-ESP/ConsFactura',
      campoBusqueda: 'Numero de suscriptor',
      periocidad: 'bimestral',
      descripcion: 'Acueducto y alcantarillado',
      monto: 185000,
      mes: '2026-05',
      estado: 'pendiente',
      fechaVencimiento: '2026-05-20',
      referencia: '123456-7',
      porcentajeInquilinos: 70,
    },
    {
      id: 'energia-2026-05',
      servicioId: 'energia',
      nombre: 'Energia electrica',
      empresa: 'CHEC',
      icono: 'Zap',
      color: '#F59E0B',
      urlPago:
        'https://www.chec.com.co/Home/Transparencia/Tramites-y-servicios/Paga-tu-factura',
      urlConsulta: 'https://www.chec.com.co',
      campoBusqueda: 'Numero de cuenta',
      periocidad: 'mensual',
      descripcion: 'Distribucion y comercializacion de energia',
      monto: 215000,
      mes: '2026-05',
      estado: 'vencido',
      fechaVencimiento: '2026-05-15',
      referencia: 'CHEC-102990',
      porcentajeInquilinos: 70,
    },
    {
      id: 'gas-2026-05',
      servicioId: 'gas',
      nombre: 'Gas natural',
      empresa: 'Efigas',
      icono: 'Flame',
      color: '#F97316',
      urlPago: 'https://clientes.efigas.com.co',
      urlConsulta: 'https://clientes.efigas.com.co',
      campoBusqueda: 'Numero de contrato',
      periocidad: 'mensual',
      descripcion: 'Gas natural domiciliario en Manizales',
      monto: 98000,
      mes: '2026-05',
      estado: 'pendiente',
      fechaVencimiento: '2026-05-22',
      referencia: 'EF-202455',
      porcentajeInquilinos: 70,
    },
    {
      id: 'internet-2026-05',
      servicioId: 'internet',
      nombre: 'Internet / Television',
      empresa: 'Claro (Telmex)',
      icono: 'Wifi',
      color: '#6366F1',
      urlPago: 'https://telmex.com/web/hogar/mi-telmex',
      urlConsulta:
        'https://telmex.com/web/asistencia/canales-digitales-de-pago',
      campoBusqueda: 'Numero de cuenta / referencia de pago',
      periocidad: 'mensual',
      descripcion: 'Servicio de internet y/o television',
      monto: 165000,
      mes: '2026-05',
      estado: 'pendiente',
      fechaVencimiento: '2026-05-25',
      referencia: 'CL-87878',
      porcentajeInquilinos: 70,
    },
    {
      id: 'arriendo-2026-05',
      servicioId: 'arriendo_base',
      nombre: 'Arriendo apartamento',
      empresa: 'Propietario',
      icono: 'Home',
      color: '#1A3C5E',
      urlPago: null,
      periocidad: 'mensual',
      descripcion: 'Arriendo que pagas al dueno del apartamento',
      monto: 1350000,
      mes: '2026-05',
      estado: 'pendiente',
      fechaVencimiento: '2026-05-30',
      referencia: 'AP-0501',
      porcentajeInquilinos: 0,
    },
  ],
  serviciosHabitacion: [
    { id: 'sh1', habitacionId: 'h1', monto: 140000 },
    { id: 'sh2', habitacionId: 'h1', monto: 160000 },
    { id: 'sh3', habitacionId: 'h1', monto: 175000 },
    { id: 'sh4', habitacionId: 'h2', monto: 130000 },
    { id: 'sh5', habitacionId: 'h2', monto: 135000 },
    { id: 'sh6', habitacionId: 'h2', monto: 150000 },
  ],
  serviciosPagos: [],
}
