export const SERVICIOS_MANIZALES = [
  {
    id: 'agua',
    nombre: 'Agua y alcantarillado',
    empresa: 'Aguas de Manizales',
    icono: 'Droplet',
    color: '#0EA5E9',
    urlPago:
      'https://portal.aguasdemanizales.com.co/Portal/Modulos/Pagos/InicioPago.aspx',
    urlConsulta: 'https://www.aguasdemanizales.com.co/Aguas-de-Manizales-SA-ESP/ConsFactura',
    whatsapp: '+573102545775',
    telefono: '(606) 887-9770',
    campoBusqueda: 'Numero de suscriptor',
    periocidad: 'bimestral',
    descripcion: 'Acueducto y alcantarillado',
  },
  {
    id: 'energia',
    nombre: 'Energia electrica',
    empresa: 'CHEC',
    icono: 'Zap',
    color: '#F59E0B',
    urlPago: 'https://www.chec.com.co/Home/Transparencia/Tramites-y-servicios/Paga-tu-factura',
    urlConsulta: 'https://www.chec.com.co',
    campoBusqueda: 'Numero de cuenta',
    periocidad: 'mensual',
    descripcion: 'Distribucion y comercializacion de energia',
  },
  {
    id: 'gas',
    nombre: 'Gas natural',
    empresa: 'Efigas',
    icono: 'Flame',
    color: '#F97316',
    urlPago: 'https://clientes.efigas.com.co',
    urlConsulta: 'https://clientes.efigas.com.co',
    campoBusqueda: 'Numero de contrato',
    periocidad: 'mensual',
    descripcion: 'Gas natural domiciliario en Manizales',
    direccion: 'Av. Kevin Angel #70-70, Manizales',
  },
  {
    id: 'internet',
    nombre: 'Internet / Television',
    empresa: 'Claro (Telmex)',
    empresaAlternativa: 'UNE / ETB',
    icono: 'Wifi',
    color: '#6366F1',
    urlPago: 'https://telmex.com/web/hogar/mi-telmex',
    urlConsulta: 'https://telmex.com/web/asistencia/canales-digitales-de-pago',
    campoBusqueda: 'Numero de cuenta / referencia de pago',
    periocidad: 'mensual',
    descripcion: 'Servicio de internet y/o television',
    nota: 'Tambien puedes pagar en la app Nequi o Bancolombia',
  },
  {
    id: 'arriendo_base',
    nombre: 'Arriendo apartamento',
    empresa: 'Propietario',
    icono: 'Home',
    color: '#1A3C5E',
    urlPago: null,
    periocidad: 'mensual',
    descripcion: 'Arriendo que pagas al dueno del apartamento',
  },
]

export const METODOS_PAGO_CO = [
  { id: 'nequi', nombre: 'Nequi', icono: 'Sparkles' },
  { id: 'daviplata', nombre: 'Daviplata', icono: 'Wallet' },
  { id: 'bancolombia', nombre: 'Bancolombia', icono: 'Banknote' },
  { id: 'pse', nombre: 'PSE', icono: 'Landmark' },
  { id: 'efectivo', nombre: 'Efectivo', icono: 'Coins' },
  { id: 'transferencia', nombre: 'Transferencia', icono: 'ArrowLeftRight' },
]
